name: zviewer
description: A multimedia viewer application for images and videos
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  photo_view: ^0.14.0
  video_player: ^2.8.1
  path_provider: ^2.1.1
  provider: ^6.1.1
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.9
  file_picker: ^8.0.0+1
  cached_network_image: ^3.3.0
  webp: ^0.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/logo/

# 应用图标配置
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/zviewer-logo-512.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo/zviewer-logo-512.png"
    background_color: "#1a1a1a"
    theme_color: "#007AFF"
  windows:
    generate: true
    image_path: "assets/logo/zviewer-logo-512.png"
    icon_size: 48
