version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: zviewer
      POSTGRES_USER: zviewer
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zviewer -d zviewer"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=development
      - SERVER_PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=zviewer
      - DB_PASSWORD=password
      - DB_NAME=zviewer
      - DB_SSLMODE=disable
      - JWT_SECRET=your-secret-key-change-in-production
      - JWT_EXPIRATION=24h
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/app/migrations

volumes:
  postgres_data:
