global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'zviewer-cluster'
    replica: 'prometheus-1'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s

  # Main server
  - job_name: 'main-server'
    static_configs:
      - targets: ['main-server:8080']
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 5s

  # Media service
  - job_name: 'media-service'
    static_configs:
      - targets: ['media-service:8081']
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 5s

  # Comments service
  - job_name: 'comments-service'
    static_configs:
      - targets: ['comments-service:8082']
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 5s

  # Payments service
  - job_name: 'payments-service'
    static_configs:
      - targets: ['payments-service:8083']
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 5s

  # Admin service
  - job_name: 'admin-service'
    static_configs:
      - targets: ['admin-service:8084']
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 5s

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: /nginx_status
    scrape_interval: 10s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 10s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 10s

  # Node exporter (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s

  # cAdvisor (if available)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s
