// Mocks generated by Mockito 5.4.6 from annotations
// in zviewer/test/widgets/admin/admin_dashboard_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:zviewer/models/admin_action.dart' as _i9;
import 'package:zviewer/models/content_category.dart' as _i4;
import 'package:zviewer/models/content_item.dart' as _i3;
import 'package:zviewer/providers/auth_provider.dart' as _i5;
import 'package:zviewer/providers/content_management_provider.dart' as _i8;
import 'package:zviewer/services/content_management_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeContentListResponse_0 extends _i1.SmartFake
    implements _i2.ContentListResponse {
  _FakeContentListResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeContentItem_1 extends _i1.SmartFake implements _i3.ContentItem {
  _FakeContentItem_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeContentActionResponse_2 extends _i1.SmartFake
    implements _i2.ContentActionResponse {
  _FakeContentActionResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBulkActionResponse_3 extends _i1.SmartFake
    implements _i2.BulkActionResponse {
  _FakeBulkActionResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeContentCategory_4 extends _i1.SmartFake
    implements _i4.ContentCategory {
  _FakeContentCategory_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i5.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isAdmin => (super.noSuchMethod(
        Invocation.getter(#isAdmin),
        returnValue: false,
      ) as bool);

  @override
  bool get isModerator => (super.noSuchMethod(
        Invocation.getter(#isModerator),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> register(
    String? email,
    String? password,
    String? confirmPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            email,
            password,
            confirmPassword,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> refreshUser() => (super.noSuchMethod(
        Invocation.method(
          #refreshUser,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ContentManagementProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockContentManagementProvider extends _i1.Mock
    implements _i8.ContentManagementProvider {
  MockContentManagementProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.ContentItem> get content => (super.noSuchMethod(
        Invocation.getter(#content),
        returnValue: <_i3.ContentItem>[],
      ) as List<_i3.ContentItem>);

  @override
  List<_i4.ContentCategory> get categories => (super.noSuchMethod(
        Invocation.getter(#categories),
        returnValue: <_i4.ContentCategory>[],
      ) as List<_i4.ContentCategory>);

  @override
  List<_i9.AdminAction> get recentActions => (super.noSuchMethod(
        Invocation.getter(#recentActions),
        returnValue: <_i9.AdminAction>[],
      ) as List<_i9.AdminAction>);

  @override
  List<_i9.AdminAction> get contentAdminActions => (super.noSuchMethod(
        Invocation.getter(#contentAdminActions),
        returnValue: <_i9.AdminAction>[],
      ) as List<_i9.AdminAction>);

  @override
  Set<String> get selectedContentIds => (super.noSuchMethod(
        Invocation.getter(#selectedContentIds),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  String get searchQuery => (super.noSuchMethod(
        Invocation.getter(#searchQuery),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#searchQuery),
        ),
      ) as String);

  @override
  String get userFilter => (super.noSuchMethod(
        Invocation.getter(#userFilter),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#userFilter),
        ),
      ) as String);

  @override
  Set<String> get selectedCategories => (super.noSuchMethod(
        Invocation.getter(#selectedCategories),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  String get sortBy => (super.noSuchMethod(
        Invocation.getter(#sortBy),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#sortBy),
        ),
      ) as String);

  @override
  String get sortOrder => (super.noSuchMethod(
        Invocation.getter(#sortOrder),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#sortOrder),
        ),
      ) as String);

  @override
  int get currentPage => (super.noSuchMethod(
        Invocation.getter(#currentPage),
        returnValue: 0,
      ) as int);

  @override
  int get totalPages => (super.noSuchMethod(
        Invocation.getter(#totalPages),
        returnValue: 0,
      ) as int);

  @override
  int get totalContent => (super.noSuchMethod(
        Invocation.getter(#totalContent),
        returnValue: 0,
      ) as int);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  int get pendingContent => (super.noSuchMethod(
        Invocation.getter(#pendingContent),
        returnValue: 0,
      ) as int);

  @override
  int get approvedContent => (super.noSuchMethod(
        Invocation.getter(#approvedContent),
        returnValue: 0,
      ) as int);

  @override
  int get rejectedContent => (super.noSuchMethod(
        Invocation.getter(#rejectedContent),
        returnValue: 0,
      ) as int);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> loadContent({bool? refresh = false}) => (super.noSuchMethod(
        Invocation.method(
          #loadContent,
          [],
          {#refresh: refresh},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> loadCategories() => (super.noSuchMethod(
        Invocation.method(
          #loadCategories,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> loadRecentActions({int? limit = 50}) => (super.noSuchMethod(
        Invocation.method(
          #loadRecentActions,
          [],
          {#limit: limit},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> loadContentAdminActions(String? contentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadContentAdminActions,
          [contentId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> approveContent(String? contentId) => (super.noSuchMethod(
        Invocation.method(
          #approveContent,
          [contentId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> rejectContent(
    String? contentId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #rejectContent,
          [
            contentId,
            reason,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteContent(
    String? contentId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteContent,
          [
            contentId,
            reason,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> categorizeContent(
    String? contentId,
    List<String>? categories,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #categorizeContent,
          [
            contentId,
            categories,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> performBulkAction(
    String? action,
    List<String>? contentIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #performBulkAction,
          [
            action,
            contentIds,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> createCategory(_i4.ContentCategory? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCategory,
          [category],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateCategory(_i4.ContentCategory? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [category],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteCategory(String? categoryId) => (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [categoryId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void setSearch(String? query) => super.noSuchMethod(
        Invocation.method(
          #setSearch,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setStatusFilter(_i3.ContentStatus? status) => super.noSuchMethod(
        Invocation.method(
          #setStatusFilter,
          [status],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTypeFilter(_i3.ContentType? type) => super.noSuchMethod(
        Invocation.method(
          #setTypeFilter,
          [type],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setUserFilter(String? user) => super.noSuchMethod(
        Invocation.method(
          #setUserFilter,
          [user],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setStartDate(DateTime? date) => super.noSuchMethod(
        Invocation.method(
          #setStartDate,
          [date],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setEndDate(DateTime? date) => super.noSuchMethod(
        Invocation.method(
          #setEndDate,
          [date],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleCategoryFilter(
    String? categoryId,
    bool? selected,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #toggleCategoryFilter,
          [
            categoryId,
            selected,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSorting(
    String? sortBy,
    String? sortOrder,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setSorting,
          [
            sortBy,
            sortOrder,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearAllFilters() => super.noSuchMethod(
        Invocation.method(
          #clearAllFilters,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void applyFilters() => super.noSuchMethod(
        Invocation.method(
          #applyFilters,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleContentSelection(
    String? contentId,
    bool? selected,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #toggleContentSelection,
          [
            contentId,
            selected,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectAllContent() => super.noSuchMethod(
        Invocation.method(
          #selectAllContent,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearSelection() => super.noSuchMethod(
        Invocation.method(
          #clearSelection,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> loadNextPage() => (super.noSuchMethod(
        Invocation.method(
          #loadNextPage,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> loadPreviousPage() => (super.noSuchMethod(
        Invocation.method(
          #loadPreviousPage,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> refreshAll() => (super.noSuchMethod(
        Invocation.method(
          #refreshAll,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ContentManagementService].
///
/// See the documentation for Mockito's code generation for more information.
class MockContentManagementService extends _i1.Mock
    implements _i2.ContentManagementService {
  MockContentManagementService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.ContentListResponse> getContentList({
    int? page = 1,
    int? limit = 20,
    _i3.ContentStatus? status,
    _i3.ContentType? type,
    String? search,
    String? userId,
    List<String>? categories,
    String? sortBy = 'uploadedAt',
    String? sortOrder = 'desc',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getContentList,
          [],
          {
            #page: page,
            #limit: limit,
            #status: status,
            #type: type,
            #search: search,
            #userId: userId,
            #categories: categories,
            #sortBy: sortBy,
            #sortOrder: sortOrder,
          },
        ),
        returnValue: _i6.Future<_i2.ContentListResponse>.value(
            _FakeContentListResponse_0(
          this,
          Invocation.method(
            #getContentList,
            [],
            {
              #page: page,
              #limit: limit,
              #status: status,
              #type: type,
              #search: search,
              #userId: userId,
              #categories: categories,
              #sortBy: sortBy,
              #sortOrder: sortOrder,
            },
          ),
        )),
      ) as _i6.Future<_i2.ContentListResponse>);

  @override
  _i6.Future<_i3.ContentItem> getContentItem(String? contentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getContentItem,
          [contentId],
        ),
        returnValue: _i6.Future<_i3.ContentItem>.value(_FakeContentItem_1(
          this,
          Invocation.method(
            #getContentItem,
            [contentId],
          ),
        )),
      ) as _i6.Future<_i3.ContentItem>);

  @override
  _i6.Future<_i2.ContentActionResponse> approveContent(String? contentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #approveContent,
          [contentId],
        ),
        returnValue: _i6.Future<_i2.ContentActionResponse>.value(
            _FakeContentActionResponse_2(
          this,
          Invocation.method(
            #approveContent,
            [contentId],
          ),
        )),
      ) as _i6.Future<_i2.ContentActionResponse>);

  @override
  _i6.Future<_i2.ContentActionResponse> rejectContent(
    String? contentId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #rejectContent,
          [
            contentId,
            reason,
          ],
        ),
        returnValue: _i6.Future<_i2.ContentActionResponse>.value(
            _FakeContentActionResponse_2(
          this,
          Invocation.method(
            #rejectContent,
            [
              contentId,
              reason,
            ],
          ),
        )),
      ) as _i6.Future<_i2.ContentActionResponse>);

  @override
  _i6.Future<_i2.ContentActionResponse> deleteContent(
    String? contentId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteContent,
          [
            contentId,
            reason,
          ],
        ),
        returnValue: _i6.Future<_i2.ContentActionResponse>.value(
            _FakeContentActionResponse_2(
          this,
          Invocation.method(
            #deleteContent,
            [
              contentId,
              reason,
            ],
          ),
        )),
      ) as _i6.Future<_i2.ContentActionResponse>);

  @override
  _i6.Future<_i2.ContentActionResponse> categorizeContent(
    String? contentId,
    List<String>? categories,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #categorizeContent,
          [
            contentId,
            categories,
          ],
        ),
        returnValue: _i6.Future<_i2.ContentActionResponse>.value(
            _FakeContentActionResponse_2(
          this,
          Invocation.method(
            #categorizeContent,
            [
              contentId,
              categories,
            ],
          ),
        )),
      ) as _i6.Future<_i2.ContentActionResponse>);

  @override
  _i6.Future<_i2.BulkActionResponse> bulkAction(
    String? action,
    List<String>? contentIds, {
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #bulkAction,
          [
            action,
            contentIds,
          ],
          {#metadata: metadata},
        ),
        returnValue:
            _i6.Future<_i2.BulkActionResponse>.value(_FakeBulkActionResponse_3(
          this,
          Invocation.method(
            #bulkAction,
            [
              action,
              contentIds,
            ],
            {#metadata: metadata},
          ),
        )),
      ) as _i6.Future<_i2.BulkActionResponse>);

  @override
  _i6.Future<List<_i4.ContentCategory>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i6.Future<List<_i4.ContentCategory>>.value(
            <_i4.ContentCategory>[]),
      ) as _i6.Future<List<_i4.ContentCategory>>);

  @override
  _i6.Future<_i4.ContentCategory> createCategory(
          _i4.ContentCategory? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCategory,
          [category],
        ),
        returnValue:
            _i6.Future<_i4.ContentCategory>.value(_FakeContentCategory_4(
          this,
          Invocation.method(
            #createCategory,
            [category],
          ),
        )),
      ) as _i6.Future<_i4.ContentCategory>);

  @override
  _i6.Future<_i4.ContentCategory> updateCategory(
          _i4.ContentCategory? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [category],
        ),
        returnValue:
            _i6.Future<_i4.ContentCategory>.value(_FakeContentCategory_4(
          this,
          Invocation.method(
            #updateCategory,
            [category],
          ),
        )),
      ) as _i6.Future<_i4.ContentCategory>);

  @override
  _i6.Future<bool> deleteCategory(String? categoryId) => (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [categoryId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<List<_i9.AdminAction>> getContentAdminActions(String? contentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getContentAdminActions,
          [contentId],
        ),
        returnValue:
            _i6.Future<List<_i9.AdminAction>>.value(<_i9.AdminAction>[]),
      ) as _i6.Future<List<_i9.AdminAction>>);

  @override
  _i6.Future<List<_i9.AdminAction>> getRecentAdminActions({
    int? limit = 50,
    String? adminId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentAdminActions,
          [],
          {
            #limit: limit,
            #adminId: adminId,
          },
        ),
        returnValue:
            _i6.Future<List<_i9.AdminAction>>.value(<_i9.AdminAction>[]),
      ) as _i6.Future<List<_i9.AdminAction>>);
}
